### ISSUE TITLE
No continents

### ISSUE THREAD

**Issue by AdrienMarquer** [TarekMostafa/ChampionshipApp#1]
Hi, i can't create teams because the list of continents is empty, is there something to import or to create in the database ?

Plus i'm really interested in your project cause i'm also doing a tournament app in vuejs/firebase (beginner), would it be possible to ask you some informations about the database architecture please ? my mail : adr.marquer@gmail.com

**Comment by TarekMostafa** [comment]
[teams.txt](https://github.com/TarekMostafa/ChampionshipApp/files/3075472/teams.txt)

This file contains all national teams, as continents come from teams collection

**Comment by AdrienMarquer** [comment]
Hi,

Thank you really much for the infos,

You said that you will change the database structure and actually i'm
struggling to create mine. Same thing, i got teams, groups and then final
stage and a ranking page (sort per goals, wins...).
Being new to the NoSQL document typed database i struggle to find the best
way to structure the data, both groups and final stage needs to be linked
to matchs, but in your opinion what is the best way to differentiate a
group match and a stage match ?

Best regards and thank you for your time,

Adrien Marquer

Le sam. 13 avr. 2019 à 01:39, Tarek Mostafa <notifications@github.com> a
écrit :
